version: "3.3"

services:
  packer:
    build: 
      dockerfile: Dockerfile.dev
      context: ./prod/packer
    volumes:
      - ${PWD}/prod/packer:/packer
      - ${PWD}/prod/xplat:/xplat
    ports:
      - "7777:8000"
    networks:
      - infra-private
      - default
    environment:
      - DB_URL=http://couchdb:5984
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:12201"

networks:
  infra-private:
    external: true
  default:
    driver: "bridge"