version: "3.3"

services:
  packer:
    build: 
      dockerfile: Dockerfile.dev
      context: ./prod/packer
    volumes:
      - ${PWD}/prod/packer:/packer
    ports:
      - "7777:8000"
    networks:
      - infra-private
      - default
    environment:
      - DB_URL=http://couchdb:5984

networks:
  infra-private:
    external: true
  default:
    driver: "bridge"