version: "3.3"

networks:
  infra-private:
    external: true

services:
  elasticsearch:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - ${PWD}/data/es:/usr/share/elasticsearch/data
    networks:
      - infra-private
    deploy:
      placement:
        constraints:
          - node.role == manager
  kibana:
    image: kibana:7.14.1
    depends_on:
      - elasticsearch
    networks:
      - infra-private
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=infra-private
        - traefik.http.routers.kibana.rule=Host(`kibana.${INFRA_DOMAIN}`)
        - traefik.http.routers.kibana.entrypoints=https
        - traefik.http.routers.kibana.middlewares=middlewares0
        - traefik.http.services.kibana.loadbalancer.server.port=5601
        - traefik.http.middlewares.middlewares0.basicauth.users=${INFRA_ADMIN_USER}:${INFRA_ADMIN_HASHED_PASSWORD}
        - traefik.public.service=yes
      placement:
        constraints:
          - node.role == manager
  logstash:
    image: logstash:7.14.1
    depends_on:
      - elasticsearch
    configs:
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "12201:12201/udp"
    deploy:
      mode: global
    networks:
      - infra-private

configs:
  logstash_pipeline:
    file: ${PWD}/conf/logstash.conf

volumes:
  infra_es:
    driver: local
