version: "3.3"

networks:
  default:
    driver: overlay
    internal: true
  infra-private:
    external: true

services:
  node-exporter:
    image: prom/node-exporter:v1.2.2
    networks:
      - default
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      # - /etc/hostname:/etc/nodename
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.textfile.directory=/etc/node-exporter
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
      - --no-collector.ipvs
    deploy:
      # A node signal collector is going to run on every node.
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  prometheus:
    image: prom/prometheus:v2.30.3
    networks:
      - infra-private
      - default
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=24h
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yaml
    volumes:
      - prometheus:/prometheus
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M
      labels:
        - traefik.enable=true
        - traefik.docker.network=infra-private
        - traefik.http.routers.prometheus.rule=Host(`prometheus.${INFRA_DOMAIN}`)
        - traefik.http.routers.prometheus.entrypoints=https
        - traefik.http.services.prometheus.loadbalancer.server.port=9090
        - traefik.public.service=yes
  cadvisor:
    # Following image is for an Apple silicon.
    # If you are on other platforms, please use the official channel.
    # image: gcr.io/cadvisor/cadvisor:v0.41.0-containerd-fix-rc.2
    image: zcube/cadvisor:latest
    networks:
      - default
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    logging:
      driver: "gelf"
      options:
        gelf-address: ${INFRA_GELF_ADDRESS}
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  grafna:
    image: grafana/grafana:8.1.7
    networks:
      - infra-private
    environment:
      - GF_SECURITY_ADMIN_USER=${INFRA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${INFRA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana:/var/lib/grafana
      - grafana_dashboard:/etc/grafana/dashboards/
    configs:
      - source: grafana_prometheus
        target: /etc/grafana/provisioning/datasources/prometheus.yaml
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.docker.network=infra-public
        - traefik.http.routers.grafana.rule=Host(`grafana.${INFRA_DOMAIN}`)
        - traefik.http.routers.grafana.entrypoints=https
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - traefik.public.service=yes

configs:
  prometheus_config:
    file: ${PWD}/conf/prometheus.yaml
  grafana_prometheus:
    file: ${PWD}/conf/grafana_prometheus.yaml

volumes:
  prometheus:
  grafana:
  grafana_dashboard:
