#!/bin/bash

command=${1}
shift

ensure_network() {
  local name=$1
  shift
  local filtered=$(docker network ls --filter name=$name --format {{.Name}})
  if [[ $name = $filtered ]]; then
    return 0
  fi
  echo "network: created - $(docker network create $@ $name)"
}

ensure_network 'infra-public' --driver=overlay --attachable
ensure_network 'infra-private' --driver=overlay --attachable --internal

case ${command} in
  lb)
    ./stack.sh lb infra_lb.yaml $@
    ;;
  logs)
    ./stack.sh logs infra_logs.yaml $@
    ;;
  db)
    ./stack.sh db infra_db.yaml $@
    ;;
  node)
    nodeid=$(docker info -f '{{.Swarm.NodeID}}')
    subcmd=$1
    shift
    case ${subcmd} in
      id)
        echo ${nodeid}
        ;;
      add-label)
        docker node update --label-add $@ ${nodeid}
        echo "node labels: $(docker node inspect --format '{{.Spec.Labels}}' ${nodeid})"
        ;;
    esac
    ;;
  init)
    mkdir -p ${PWD}/data/es
    mkdir -p ${PWD}/data/traefik/cert
    mkdir -p ${PWD}/data/couchdb
    mkdir -p ${PWD}/data/influxdb
    ;;
  *)
    echo "info node id -- node id"
    ;;
esac


