version: "3.3"

services:
  couchdb:
    image: couchdb:2.3.1
    volumes:
      - ${PWD}/data/couchdb:/opt/couchdb/data
    networks:
      - infra-private
    logging:
      driver: "gelf"
      options:
        gelf-address: ${INFRA_GELF_ADDRESS}
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M
      placement:
        constraints:
          - node.labels.db == true
  influxdb:
    image: influxdb:1.7
    volumes:
      - ${PWD}/data/influxdb:/var/lib/influxdb
    networks:
      - infra-private
    logging:
      driver: "gelf"
      options:
        gelf-address: ${INFRA_GELF_ADDRESS}
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 512M
        reservations:
          cpus: "0.3"
          memory: 128M
      placement:
        constraints:
          - node.labels.db == true
  postgres:
    image: postgres:9.6.23-bullseye
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${INFRA_ADMIN_PASSWORD}
      - POSTGRES_USER=${INFRA_ADMIN_USER}

networks:
  infra-private:
    external: true

volumes:
  postgresdb:
