version: "3.3"

services:
  elasticsearch:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - infra_es:/usr/share/elasticsearch/data
    networks:
      - infra-private
    deploy:
      placement:
        constraints:
          - node.role == manager
  kibana:
    image: kibana:7.14.1
    depends_on:
      - elasticsearch
    networks:
      - infra-private
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=infra-private
        - traefik.http.routers.kibana.rule=Host(`kibana.${INFRA_DOMAIN}`)
        - traefik.http.routers.kibana.entrypoints=https
        - traefik.http.services.kibana.loadbalancer.server.port=5601
        - traefik.public.service=yes
      placement:
        constraints:
          - node.role == manager
  logstash:
    image: logstash:7.14.1
    depends_on:
      - elasticsearch
    configs:
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "12201:12201/udp"
    deploy:
      mode: global
    networks:
      - infra-private
  snorkel:
    image: ${INFRA_IMAGE_NAME_SNORKEL}
    networks:
      - infra-private
    volumes:
      - sybil:/sybil
      - snorkeldb:/root/.local/share/snorkel
    environment:
      - SNORKEL_NO_AUTH=true
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=infra-private
        - traefik.http.routers.snorkel.rule=Host(`snorkel.${INFRA_DOMAIN}`)
        - traefik.http.routers.snorkel.entrypoints=https
        - traefik.http.services.snorkel.loadbalancer.server.port=2333
        - traefik.public.service=yes
      placement:
        constraints:
          - node.role == manager
  snorkel-relay:
    image: ${INFRA_IMAGE_NAME_SNORKEL_RELAY}
    networks:
      - infra-private
    volumes:
      - sybil:/sybil:ro
      - snorkeldb:/snorkeldb
    depends_on:
      - snorkel
    command:
      [
        "snorkel-relay",
        "--sybil",
        "/sybil/snorkel.sybil",
        "--db",
        "/snorkeldb",
        "--token",
        "__snorkel-relay__",
      ]
  clogs:
    image: ${INFRA_IMAGE_NAME_CLOGS}
    networks:
      - infra-private
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=infra-private
        - traefik.http.routers.clogs.rule=Path(`/clogs/log`)
        - traefik.http.routers.clogs.entrypoints=https
        - traefik.http.services.clogs.loadbalancer.server.port=9977
        - traefik.public.service=yes


configs:
  logstash_pipeline:
    file: ${PWD}/conf/logstash.conf

volumes:
  infra_es:
  sybil:
  snorkeldb:

networks:
  infra-private:
    external: true
