FROM python

ENV PYTHONPATH "${PYTHONPATH}:/xplat/snorkel-py"

WORKDIR /packer
RUN apt-get update && apt-get install -y python3-pip iputils-ping iproute2 
RUN pip install fastapi CouchDB "uvicorn[standard]" autopep8

CMD uvicorn main:app --reload --host 0.0.0.0