version: "3.3"

services:
  unleash-postgres:
    image: postgres:9.6.23-bullseye
    volumes:
      - postgresdb:/var/lib/postgresql/data
    networks:
      - infra-private
    environment:
      - POSTGRES_PASSWORD=${INFRA_ADMIN_PASSWORD}
      - POSTGRES_USER=${INFRA_ADMIN_USER}
  unleash:
    image: ${INFRA_IMAGE_NAME_UNLEASH}
    networks:
      - infra-private
    environment:
      DATABASE_URL: "postgres://${INFRA_ADMIN_USER}:${INFRA_ADMIN_PASSWORD}@unleash-postgres/postgres"
      DATABASE_SSL: "false"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.public.service=yes
        - traefik.docker.network=infra-private
        - traefik.docker.lbswarm=true
        - traefik.http.routers.unleash.entrypoints=https
        - traefik.http.routers.unleash.rule=Host(`unleash.${INFRA_DOMAIN}`)
        - traefik.http.services.unleash.loadbalancer.server.port=4242

volumes:
  flipt:
  postgresdb:

networks:
  infra-private:
    external: true
