version: "3.3"

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - default
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer
    command: -H tcp://agent:9001 --tlsskipverify
    volumes:
      - portainer:/data
    networks:
      - default
      - infra-private
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=infra-private
        - traefik.http.routers.portainer.rule=Host(`portainer.${INFRA_DOMAIN}`)
        - traefik.http.routers.portainer.entrypoints=https
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        - traefik.public.service=yes

networks:
  default:
    attachable: true
    internal: true
  infra-private:
    external: true

volumes:
  portainer:
